# Generated by Django 3.2.9 on 2022-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
