# Generated by Django 3.2.9 on 2022-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quiz_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficluty',
        ),
        migrations.AddField(
            model_name='quiz',
            name='subjects',
            field=models.CharField(choices=[('php', 'php'), ('asp.net', 'asp.net'), ('java', 'java')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
