# Generated by Django 3.2.9 on 2022-02-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_auto_20220227_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='subjects',
            new_name='subject',
        ),
    ]
