# Generated by Django 3.2.9 on 2022-02-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220225_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserstudent',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customuserstudent',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuserstudent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
